#!/bin/sh
export PATH=/bin:/usr/bin:/sbin:/usr/sbin
/usr/sbin/busybox mount -t proc proc /proc
/usr/sbin/busybox mount -t sysfs sys /sys
/usr/sbin/busybox mdev -s
echo ifconfig -a:
/usr/sbin/ifconfig -a
echo lsmod:
/usr/sbin/busybox lsmod
export PYUDEV_UDEV_LIBRARY_NAME=libudev.so.1
exec /bin/python2.7 -m inaugurator.main
