#!/bin/sh
export PATH=/bin:/usr/bin:/sbin:/usr/sbin
/usr/sbin/busybox mount -t proc proc /proc
/usr/sbin/busybox mount -t sysfs sys /sys
/usr/sbin/busybox mdev -s
echo ifconfig -a:
/usr/sbin/ifconfig -a
/usr/sbin/busybox modprobe virtio_blk
/usr/sbin/busybox modprobe virtio_net
/usr/sbin/busybox modprobe dm-mod
/usr/sbin/busybox modprobe sd_mod
/usr/sbin/busybox modprobe ahci
/usr/sbin/busybox modprobe ext4
echo lsmod:
/usr/sbin/busybox lsmod
export PYUDEV_UDEV_LIBRARY_NAME=libudev.so.1
export PYTHONPATH=$PYTHONPATH:/usr/lib/osmosis-1.1.0b1-py2.7.egg
exec /bin/python2.7 -m inaugurator.main
