#!/bin/sh
export PATH=/bin:/usr/bin:/sbin:/usr/sbin
/usr/sbin/busybox mount -t proc proc /proc
/usr/sbin/busybox mount -t sysfs sys /sys
/usr/sbin/busybox mdev -s
/usr/sbin/mkdir -p /dev/pts
/usr/sbin/busybox mount -t devpts none /dev/pts
/usr/sbin/telnetd -l /bin/bash
echo ifconfig -a:
/usr/sbin/ifconfig -a
/usr/sbin/busybox modprobe virtio_blk
/usr/sbin/busybox modprobe virtio_net
/usr/sbin/busybox modprobe dm-mod
/usr/sbin/busybox modprobe sd_mod
/usr/sbin/busybox modprobe ahci
/usr/sbin/busybox modprobe ext4
/usr/sbin/busybox modprobe nvme
/usr/sbin/busybox modprobe dax_pmem
/usr/sbin/busybox modprobe nd_pmem
wait
/usr/sbin/busybox mdev -s
echo lsmod:
/usr/sbin/busybox lsmod
export PYUDEV_UDEV_LIBRARY_NAME=libudev.so.1
exec /bin/python2.7 -m inaugurator.main
