AS_GENERATED_BY_A_SIMPLE_FEDORA = """
#
# DO NOT EDIT THIS FILE
#
# It is automatically generated by grub2-mkconfig using templates
# from /etc/grub.d and settings from /etc/default/grub
#

### BEGIN /etc/grub.d/00_header ###
if [ -s $prefix/grubenv ]; then
  load_env
fi
if [ "${next_entry}" ] ; then
   set default="${next_entry}"
   set next_entry=
   save_env next_entry
   set boot_once=true
else
   set default="0"
fi

if [ x"${feature_menuentry_id}" = xy ]; then
  menuentry_id_option="--id"
else
  menuentry_id_option=""
fi

export menuentry_id_option

if [ "${prev_saved_entry}" ]; then
  set saved_entry="${prev_saved_entry}"
  save_env saved_entry
  set prev_saved_entry=
  save_env prev_saved_entry
  set boot_once=true
fi

function savedefault {
  if [ -z "${boot_once}" ]; then
    saved_entry="${chosen}"
    save_env saved_entry
  fi
}

function load_video {
  if [ x$feature_all_video_module = xy ]; then
    insmod all_video
  else
    insmod efi_gop
    insmod efi_uga
    insmod ieee1275_fb
    insmod vbe
    insmod vga
    insmod video_bochs
    insmod video_cirrus
  fi
}

if [ x$feature_default_font_path = xy ] ; then
   font=unicode
else
insmod part_msdos
insmod ext2
set root='hd0,msdos2'
if [ x$feature_platform_search_hint = xy ]; then
  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos2 --hint-efi=hd0,msdos2 --hint-baremetal=ahci0,msdos2  7281ba4c-2700-4e8c-b2e8-95f97f3dce7c
else
  search --no-floppy --fs-uuid --set=root 7281ba4c-2700-4e8c-b2e8-95f97f3dce7c
fi
    font="/usr/share/grub/unicode.pf2"
fi

if loadfont $font ; then
  set gfxmode=auto
  load_video
  insmod gfxterm
  set locale_dir=$prefix/locale
  set lang=en_US
  insmod gettext
fi
terminal_output gfxterm
set timeout=5
### END /etc/grub.d/00_header ###

### BEGIN /etc/grub.d/10_linux ###
menuentry 'Fedora' --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-7281ba4c-2700-4e8c-b2e8-95f97f3dce7c' {
    load_video
    set gfxpayload=keep
    insmod gzio
    insmod part_msdos
    insmod ext2
    set root='hd0,msdos2'
    if [ x$feature_platform_search_hint = xy ]; then
      search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos2 --hint-efi=hd0,msdos2 --hint-baremetal=ahci0,msdos2  7281ba4c-2700-4e8c-b2e8-95f97f3dce7c
    else
      search --no-floppy --fs-uuid --set=root 7281ba4c-2700-4e8c-b2e8-95f97f3dce7c
    fi
    linux   /vmlinuz-3.11.9-200.fc19.x86_64 root=UUID=7281ba4c-2700-4e8c-b2e8-95f97f3dce7c ro
    initrd  /initramfs-3.11.9-200.fc19.x86_64.img
}
submenu 'Advanced options for Fedora' $menuentry_id_option 'gnulinux-advanced-7281ba4c-2700-4e8c-b2e8-95f97f3dce7c' {
    menuentry 'Fedora, with Linux 3.11.9-200.fc19.x86_64' --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-3.11.9-200.fc19.x86_64-advanced-7281ba4c-2700-4e8c-b2e8-95f97f3dce7c' {
        load_video
        set gfxpayload=keep
        insmod gzio
        insmod part_msdos
        insmod ext2
        set root='hd0,msdos2'
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos2 --hint-efi=hd0,msdos2 --hint-baremetal=ahci0,msdos2  7281ba4c-2700-4e8c-b2e8-95f97f3dce7c
        else
          search --no-floppy --fs-uuid --set=root 7281ba4c-2700-4e8c-b2e8-95f97f3dce7c
        fi
        linux   /vmlinuz-3.11.9-200.fc19.x86_64 root=UUID=7281ba4c-2700-4e8c-b2e8-95f97f3dce7c ro
        initrd  /initramfs-3.11.9-200.fc19.x86_64.img
    }
    menuentry 'Fedora, with Linux 3.11.9-200.fc19.x86_64 (recovery mode)' --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-3.11.9-200.fc19.x86_64-recovery-7281ba4c-2700-4e8c-b2e8-95f97f3dce7c' {
        load_video
        set gfxpayload=keep
        insmod gzio
        insmod part_msdos
        insmod ext2
        set root='hd0,msdos2'
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos2 --hint-efi=hd0,msdos2 --hint-baremetal=ahci0,msdos2  7281ba4c-2700-4e8c-b2e8-95f97f3dce7c
        else
          search --no-floppy --fs-uuid --set=root 7281ba4c-2700-4e8c-b2e8-95f97f3dce7c
        fi
        linux   /vmlinuz-3.11.9-200.fc19.x86_64 root=UUID=7281ba4c-2700-4e8c-b2e8-95f97f3dce7c ro single
        initrd  /initramfs-3.11.9-200.fc19.x86_64.img
    }
}

### END /etc/grub.d/10_linux ###

### BEGIN /etc/grub.d/20_linux_xen ###

### END /etc/grub.d/20_linux_xen ###

### BEGIN /etc/grub.d/20_ppc_terminfo ###
### END /etc/grub.d/20_ppc_terminfo ###

### BEGIN /etc/grub.d/30_os-prober ###
### END /etc/grub.d/30_os-prober ###

### BEGIN /etc/grub.d/40_custom ###
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
### END /etc/grub.d/40_custom ###

### BEGIN /etc/grub.d/41_custom ###
if [ -f  ${config_directory}/custom.cfg ]; then
  source ${config_directory}/custom.cfg
elif [ -z "${config_directory}" -a -f  $prefix/custom.cfg ]; then
  source $prefix/custom.cfg;
fi
### END /etc/grub.d/41_custom ###
"""
